# Generated by Django 3.1 on 2020-08-22 02:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpostapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boastroast',
            name='submissiondate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
